export const DEFAULT_MAX_POOL_SIZE = 8;
export const DEFAULT_MAX_CONCURRENT_CONNECTIONS = 200;
export const DEFAULT_MAX_DATA_FETCH_CONCURRENCY = 10;
export const DEFAULT_MAX_BUCKETS_PER_CONNECTION = 1000;
