export const DEFAULT_MAX_POOL_SIZE = 8;
export const DEFAULT_MAX_CONCURRENT_CONNECTIONS = 200;
export const DEFAULT_MAX_DATA_FETCH_CONCURRENCY = 10;
export const DEFAULT_MAX_BUCKETS_PER_CONNECTION = 1000;
export const DEFAULT_MAX_PARAMETER_QUERY_RESULTS = 1000;
export const DEFAULT_CHECKPOINT_REQUEST_RETENTION_MINUTES = 60;
export const DEFAULT_CHECKSUM_CACHE_TTL_MINUTES = 1 * 60;
