packages:
  - 'packages/*'
  - 'libs/*'
  - 'modules/*'
  - 'service'
  - 'test-client'
  # exclude packages that are inside test directories
  - '!**/test/**'

catalog:
  vitest: ^4.0.16
  '@vitest/ui': ^4.0.16
  '@vitest/coverage-v8': ^4.0.16

allowBuilds:
  # These need install scripts to download/build native modules
  '@mongodb-js/zstd': true
