packages:
  - 'packages/*'
  - 'libs/*'
  - 'modules/*'
  - 'service'
  - 'test-client'
  # exclude packages that are inside test directories
  - '!**/test/**'

catalog:
  vitest: ^4.1.0
  '@vitest/ui': ^4.1.0
  '@vitest/coverage-v8': ^4.1.0
  typescript: ~5.9.3

allowBuilds:
  # These need install scripts to download/build native modules
  '@mongodb-js/zstd': true

overrides:
  # Override to remove vitest production dependency
  # Remove once this is released: https://github.com/journeyapps-labs/common/pull/15
  '@journeyapps-labs/common-sdk@1.0.x>@journeyapps-labs/micro-streaming': '^1.0.2'
