# See the Sync Streams documentation for more information:
# https://docs.powersync.com/sync/streams/overview
config:
  edition: 3

streams:
  global:
    auto_subscribe: true
    queries:
      - SELECT * FROM lists
      - SELECT * FROM todos
