import { BucketDataSource, ParameterIndexLookupCreator } from './BucketSource.js';

export type BucketDefinitionId = string;
export type ParameterIndexId = string;

export interface BucketDataScope {
  /**
   * Stable key identifying the bucket data source.
   *
   * Generated by the storage implementation, and may be persisted.
   *
   * Must be unique per replication stream. May have duplicates over different streams, depending on storage requirements.
   */
  key: BucketDefinitionId;
  /** The prefix is the bucket name before the parameters. */
  bucketPrefix: string;
  /** Source used to generate buckets. */
  source: BucketDataSource;
}

export interface ParameterLookupScope {
  /**
   * Stable key identifying the parameter index.
   *
   * Generated by the storage implementation, and may be persisted.
   *
   * Must be unique per replication stream. May have duplicates over different streams, depending on storage requirements.
   */
  key: ParameterIndexId;

  /**
   * The lookup name + queryid is used to reference the parameter lookup record.
   *
   * In newer storage versions, lookupName = indexId, and queryId = ''.
   */
  lookupName: string;
  queryId: string;
  /** Source used to generate parameter lookups. */
  source: ParameterIndexLookupCreator;
}

export interface ParameterLookupDefinitionId {
  lookupName: string;
  queryId: string;
}

/**
 * Hydration state information for a source.
 *
 * This is what keeps track of bucket name and parameter lookup mappings for hydration. This can be used
 * both to re-use mappings across hydrations of different sync config versions, or to generate new mappings.
 */
export interface HydrationState {
  /**
   * Given a bucket data source definition, get the bucket prefix to use for it.
   */
  getBucketSourceScope(source: BucketDataSource): BucketDataScope;

  /**
   * Given a bucket parameter lookup definition, get the persistence name to use.
   */
  getParameterIndexLookupScope(source: ParameterIndexLookupCreator): ParameterLookupScope;
}

/**
 * This represents hydration state that performs no transformations.
 *
 * This is the legacy default behavior with no bucket versioning.
 */
export const DEFAULT_HYDRATION_STATE: HydrationState = {
  getBucketSourceScope(source: BucketDataSource) {
    return {
      key: source.uniqueName,
      bucketPrefix: source.uniqueName,
      source
    };
  },
  getParameterIndexLookupScope(source) {
    return {
      key: parameterLookupScopeKey(source.sourceId),
      ...source.sourceId,
      source
    };
  }
};

/**
 * Transforms bucket ids generated when evaluating the row by e.g. encoding version information.
 *
 * Because buckets are recreated on a sync config redeploy, it makes sense to use different bucket ids (otherwise, clients
 * may run into checksum errors causing a sync to take longer than necessary or breaking progress).
 *
 * So, this transformer receives the original bucket id as generated by defined sync config, and can prepend a version
 * identifier.
 *
 * Note that this transformation has not been present in older versions of the sync service. To preserve backwards
 * compatibility, sync config will not use this without an opt-in.
 *
 * This hydration state does not ensure uniqueness of keys across different sync configs, so it cannot be used
 * for incremental reprocessing / multiple sync configs per replication stream.
 */
export function versionedHydrationState(version: number): HydrationState {
  return {
    getBucketSourceScope(source: BucketDataSource): BucketDataScope {
      return {
        key: `${version}#${source.uniqueName}`,
        bucketPrefix: `${version}#${source.uniqueName}`,
        source
      };
    },

    getParameterIndexLookupScope(source: ParameterIndexLookupCreator): ParameterLookupScope {
      // No transformations applied here
      return {
        key: parameterLookupScopeKey(source.sourceId),
        ...source.sourceId,
        source
      };
    }
  };
}

export function parameterLookupScopeKey(scope: ParameterLookupDefinitionId): ParameterIndexId {
  return JSON.stringify([scope.lookupName, scope.queryId]);
}
