import { mongo } from '@powersync/lib-service-mongodb';
import { migrations } from '@powersync/service-core';
import * as storage from '../../../storage/storage-index.js';
import { MongoStorageConfig } from '../../../types/types.js';

const INDEX_NAME = 'user_id';

type DuplicateWriteCheckpointGroup = {
  _id: string | null;
  remove_ids: mongo.ObjectId[];
};

export const up: migrations.PowerSyncMigrationFunction = async (context) => {
  const {
    service_context: { configuration }
  } = context;
  const db = storage.createPowerSyncMongo(configuration.storage as MongoStorageConfig);

  try {
    // Existing databases may already have duplicate rows because the old
    // user_id index was not unique and checkpoint writes use upserts. Clean
    // those duplicates before creating the unique replacement index.
    await deduplicateWriteCheckpoints(db.write_checkpoints);

    // Keep the original index name so existing query plans and down migrations
    // continue to refer to the same logical index.
    if (await db.write_checkpoints.indexExists(INDEX_NAME)) {
      await db.write_checkpoints.dropIndex(INDEX_NAME);
    }

    await db.write_checkpoints.createIndex(
      {
        user_id: 1
      },
      { name: INDEX_NAME, unique: true }
    );
  } finally {
    await db.client.close();
  }
};

export const down: migrations.PowerSyncMigrationFunction = async (context) => {
  const {
    service_context: { configuration }
  } = context;

  const db = storage.createPowerSyncMongo(configuration.storage as MongoStorageConfig);

  try {
    // Restore the pre-migration index shape. The deduplicated data is left as-is
    if (await db.write_checkpoints.indexExists(INDEX_NAME)) {
      await db.write_checkpoints.dropIndex(INDEX_NAME);
    }

    await db.write_checkpoints.createIndex(
      {
        user_id: 1
      },
      { name: INDEX_NAME }
    );
  } finally {
    await db.client.close();
  }
};

async function deduplicateWriteCheckpoints(collection: mongo.Collection<storage.WriteCheckpointDocument>) {
  const duplicates = collection.aggregate<DuplicateWriteCheckpointGroup>([
    // The first id pushed into each group is the survivor. Prefer the largest
    // client_id because it is the newest managed write checkpoint id. The
    // timestamp and ObjectId tie-breakers keep the result deterministic if a
    // race produced duplicate rows with the same id.
    {
      $sort: {
        user_id: 1,
        client_id: -1,
        checkpoint_requested_at: -1,
        _id: -1
      }
    },
    {
      $group: {
        _id: '$user_id',
        ids: { $push: '$_id' },
        count: { $sum: 1 }
      }
    },
    {
      $match: {
        count: { $gt: 1 }
      }
    },
    {
      // Remove every id except the first sorted one for each duplicated user_id.
      $project: {
        remove_ids: {
          $slice: ['$ids', 1, { $subtract: ['$count', 1] }]
        }
      }
    }
  ]);

  for await (const duplicate of duplicates) {
    if (duplicate.remove_ids.length == 0) {
      continue;
    }
    // _id is generated by MongoDB but not part of the local WriteCheckpointDocument
    // write shape, so the delete filter needs a narrow type escape.
    await collection.deleteMany({
      _id: { $in: duplicate.remove_ids }
    } as any);
  }
}
